variables:
  LINUX_AMD64_BINARY: "immunediscover-ubuntu-x86-64.tar.gz"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/immunediscover/${CI_COMMIT_TAG}"

cache:
  key: $CI_PIPELINE_ID
  paths:
    - .julia

.script:
  script:
    - apt-get update -qq && apt-get install -y git
    - |
      julia --threads auto --project=@. -e '
        using Pkg
        Pkg.build()
        Pkg.test(coverage=true)'

.coverage:
  coverage: /Test coverage (\d+\.\d+%)/
  after_script:
    - |
      julia --threads auto -e '
        using Pkg
        Pkg.add("Coverage")
        using Coverage
        c, t = get_summary(process_folder())
        using Printf
        @printf "Test coverage %.2f%%\n" 100c / t'

build:
  image: julia:1.9
  extends:
    - .script
    - .coverage
  only:
    - main

build_binary:
  image: ubuntu:20.04
  timeout: 3h 30m
  script:
    - apt-get update -qq && apt-get install -y clang curl git
    - curl -fsSL https://install.julialang.org | sh -s -- -y
    - |
      ~/.juliaup/bin/julia --startup-file=no --threads auto --project=@. -e '
        using Pkg
        Pkg.instantiate()
        using PackageCompiler

        create_app(".", "immunediscover", include_transitive_dependencies=false, cpu_target="x86-64") '
    - tar cvfz ${LINUX_AMD64_BINARY} immunediscover
  artifacts:
    paths:
      - ${LINUX_AMD64_BINARY}
  only:
    - tags

pages:
  image: julia:1.9
  stage: deploy
  script:
    - apt-get update -qq && apt-get install -y git
    - |
      julia --threads auto --project=docs -e '
        using Pkg
        Pkg.develop(PackageSpec(path=pwd()))
        Pkg.instantiate()
        using Documenter: doctest
        using immunediscover
        doctest(immunediscover)
        include("docs/make.jl")'
    - mkdir -p public
    - mv docs/build public/dev
  artifacts:
    paths:
      - public
  only:
    - main

upload:
  stage: upload
  image: curlimages/curl:latest
  needs:
    - job: build_binary
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - ls -la
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "${LINUX_AMD64_BINARY}" "${PACKAGE_REGISTRY_URL}/${LINUX_AMD64_BINARY}"
    - echo "${LINUX_AMD64_BINARY}" "${PACKAGE_REGISTRY_URL}/${LINUX_AMD64_BINARY}"

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "COMMIT_TAG ${CI_COMMIT_TAG}, CI_JOB_TOKEN ${CI_JOB_TOKEN}"
    - |
      release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG \
        --assets-link "{\"name\":\"${LINUX_AMD64_BINARY}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${LINUX_AMD64_BINARY}\"}"

stages:
  - build
  - build_binary
  - test
  - deploy
  - upload
  - release

